name             'sprout-osx-apps'
maintainer       '@ajamviz'
maintainer_email 'ajammultimedia@gmail.com'
license          'MIT'
description      'Installs/Configures sprout-osx-apps'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.0'
supports         'mac_os_x'
depends          'sprout-base'
depends          'homebrew', '>= 1.6.6'
depends          'dmg'
